steps:
  - name: "gcr.io/cloud-builders/nodejs:20"
    entrypoint: npm
    args: ["install"]
  - name: "gcr.io/cloud-builders/nodejs:20"
    entrypoint: npm
    args: ["run", "build"]
images:
  - "asia-northeast3-docker.pkg.dev/PROJECT_ID/REPO/IMAGE_NAME:$SHORT_SHA"

# 로그를 Cloud Logging으로만 설정
options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET # 이 옵션 추가

substitutions:
  # 커밋 SHA를 참조할 수 있게 설정
  _COMMIT_SHA: ${COMMIT_SHA}

timeout: 1200s # 빌드 시간 초과 설정
